version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez row data source
    tables:
      - name: sales
        description: sales of greenweez / we have one row per products_id found in each orders_id.
        identifier: raw_gz_sales
        freshness:
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST (date_date as TIMESTAMP)"
      - name: product
        description: product of greenweez
        identifier: raw_gz_product
        columns :
        - name: products_id
          description: primary key of the table
          tests:
           - unique
           - not_null
          
      - name: ship
        description: ship of greenweez
        identifier : raw_gz_ship 
        columns:
        - name: orders_id
          description: primary key of the table
          tests:
          - unique
          - not null 
          


